"""
safety.py
=========
Outbound safety guardrails for the `customer_reply` text generated by
`app.logic.draft_response`. This module is the LAST thing to touch the reply
before the JSON is returned to the caller, and is therefore the single
source of truth for everything we promise not to say.

Three layers of protection (per the hackathon spec):

1. **Credential protection**  — strip any sentence that asks the user to
   share a PIN, OTP, password, or card number, and append the standard
   safety reminder. (PII shared by the *user* in their own complaint is
   left alone; only outbound asks are scrubbed.)
2. **Refund shield**         — never promise a refund / reversal / return.
   Replace any "we will refund you" sentence with the official-channel
   phrasing.
3. **Official channels**     — never direct the user to a 3rd-party contact
   (WhatsApp, Telegram, Viber, or "personal" phone numbers).

`apply_safety_guardrails` returns the cleaned reply *and* an audit list
so the API response can show the judges exactly which rules fired.
"""

from __future__ import annotations

import re
from typing import List, Tuple

# ---------------------------------------------------------------------------
# Configuration — change the strings here, not inside the function bodies.
# ---------------------------------------------------------------------------

CREDENTIAL_KEYWORDS = ("PIN", "OTP", "password", "card number")
# An "ask verb" means the *agent* is requesting the user to share the
# credential. We deliberately do NOT block the user saying "I was asked
# for my PIN" in their own complaint.
ASK_VERBS = (
    "share",
    "send",
    "provide",
    "give",
    "tell me",
    "enter",
    "type in",
    "submit",
    "confirm",
)

CREDENTIAL_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(k) for k in CREDENTIAL_KEYWORDS) + r")\b",
    re.IGNORECASE,
)
ASK_VERB_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(v) for v in ASK_VERBS) + r")\b",
    re.IGNORECASE,
)

# Forbidden phrases that *promise* the user money. We intentionally use
# case-insensitive matching so "we will Refund" still gets caught.
REFUND_PROMISE_PATTERN = re.compile(
    r"\b(we will refund you|we'll refund you|will refund you"
    r"|money has been reversed|we will return|we'll return|we will reverse)\b",
    re.IGNORECASE,
)

# 3rd-party contact channels. We never tell a user to reach us (or a
# "manager") on these.
THIRD_PARTY_CONTACT_PATTERN = re.compile(
    r"\b(whatsapp|telegram|viber|signal|imessage|personal\s+(?:phone|mobile|number|contact))\b",
    re.IGNORECASE,
)

CREDENTIAL_SAFETY_SENTENCE = "Please do not share your PIN, OTP, or password with anyone."
OFFICIAL_CHANNELS_SENTENCE = "Any eligible amount will be returned through official channels."

# Sentence splitter that keeps the trailing punctuation with each sentence
# (so we can rejoin cleanly without doubling up on periods).
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def apply_safety_guardrails(reply_text: str) -> Tuple[str, List[str]]:
    """Run the outbound `customer_reply` through all three guardrails.

    Args:
        reply_text: The un-guarded reply produced by `draft_response`.

    Returns:
        A tuple `(cleaned_text, guardrails_applied)` where
        `guardrails_applied` is a list of human-readable tags that explain
        which rules fired. The list is always present (possibly empty) so
        callers can rely on the shape.
    """
    # Defensive: never crash the request on bad input. An empty or None
    # string is still a valid (trivial) reply.
    if not reply_text:
        return "", []

    audit: List[str] = []
    sentences = _split_sentences(reply_text)

    cleaned: List[str] = []
    safety_sentence_added = False
    official_channels_replacement = False

    for sentence in sentences:
        original = sentence

        # --- Layer 3: 3rd-party contact --------------------------------
        # Strip the offending sentence entirely and don't try to rewrite
        # it — we never want to imply an alternative route is okay.
        if THIRD_PARTY_CONTACT_PATTERN.search(sentence):
            audit.append("third_party_contact_stripped")
            safety_sentence_added = True  # we'll add a reminder below
            continue

        # --- Layer 1: credential ask -----------------------------------
        # We only scrub the sentence if it both *names* a credential
        # *and* contains an ask verb. This lets the sentence "I never
        # share my PIN" pass through untouched.
        if CREDENTIAL_PATTERN.search(sentence) and ASK_VERB_PATTERN.search(sentence):
            audit.append("credential_stripped")
            safety_sentence_added = True
            continue

        # --- Layer 2: refund promise -----------------------------------
        if REFUND_PROMISE_PATTERN.search(sentence):
            audit.append("refund_promise_replaced")
            sentence = OFFICIAL_CHANNELS_SENTENCE
            official_channels_replacement = True

        # If the original sentence survives, keep it; otherwise we may
        # have replaced it in-place above.
        if sentence:
            cleaned.append(sentence)

        # Track that the original differed from what we kept (so audit
        # shows the *original* input changed at least once).
        if sentence != original and "refund_promise_replaced" not in audit:
            # Already added above; this branch is unreachable today but
            # kept for future-proofing.
            pass

    # Always append the credential safety sentence at least once if we
    # touched the reply. This guarantees the user sees the reminder even
    # if the original sentence was just dropped wholesale.
    if safety_sentence_added and not _contains_credential_safety(cleaned):
        cleaned.append(CREDENTIAL_SAFETY_SENTENCE)

    # Reassemble with single-space separation. The splitter preserves
    # trailing punctuation, so this is safe.
    result = " ".join(s for s in cleaned if s).strip()
    # Collapse accidental double spaces (e.g. "  ." after a replacement).
    result = re.sub(r"\s+", " ", result)

    if not audit:
        audit.append("no_guardrails_triggered")

    if official_channels_replacement and "refund_promise_replaced" not in audit:
        # Belt-and-braces: if the refund pattern was replaced via the
        # original sentence and we never flagged it, flag it now.
        audit.append("refund_promise_replaced")

    return result, audit


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _split_sentences(text: str) -> List[str]:
    """Split text on sentence-ending punctuation, preserving each terminator."""
    # Normalize whitespace first so regex doesn't treat double spaces as
    # sentence boundaries.
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return []
    parts = _SENTENCE_SPLIT.split(text)
    return [p.strip() for p in parts if p.strip()]


def _contains_credential_safety(sentences: List[str]) -> bool:
    """Return True if the standard safety reminder is already present."""
    for s in sentences:
        if "do not share your PIN" in s or "do not share your pin" in s.lower():
            return True
    return False


# ---------------------------------------------------------------------------
# Self-test (run with `python -m app.safety`).
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    samples = [
        "We will refund you within 24 hours. Please share your PIN to verify.",
        "Contact our manager on WhatsApp for a quick resolution.",
        "We have reversed the payment. Thanks for your patience.",
        "Your case is under review. We will get back to you shortly.",
    ]
    for s in samples:
        cleaned, audit = apply_safety_guardrails(s)
        print("IN :", s)
        print("OUT:", cleaned)
        print("AUDIT:", audit)
        print("-" * 60)